"use client";
import { Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "./NavAndFooter/Navbar";
import {ClerkProvider} from "@clerk/nextjs";
import {CartContext} from "./_Context/CartContext"
import { useState } from "react";

const inter = Kanit({ subsets: ["latin"], weight:"700" });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);
  return (
    <CartContext.Provider value={{cart, setCart}}>

    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
    </html>
    </ClerkProvider>
    </CartContext.Provider>
  );
}
